
export const playbookData = [
    // Phase 1: Project Initiation & Setup (Steps 1-15)
    { 
        number_index: 1, 
        name: "Price Quote",
        formal_name: "Project Proposal and Cost Estimate",
        is_deliverable: true, 
        category: 'onboarding',
        description: "Initial price quote sent to the client.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [],
        blocking_priority: "critical",
        resource_dependency: "none"
    },
    { 
        number_index: 2, 
        name: "Signed Contract from Both Parties",
        formal_name: "Master Services Agreement (MSA) Execution",
        is_deliverable: true, 
        category: 'onboarding',
        description: "Legal contract signed by both the client and the company.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [1],
        blocking_priority: "critical",
        resource_dependency: "client_materials"
    },
    { 
        number_index: 3, 
        name: "Initial Invoice Planning",
        formal_name: "Invoice and Payment Schedule Setup",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Plan the invoicing schedule based on the contract.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [2],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 4, 
        name: "PM Joins the Project",
        formal_name: "Project Manager Assignment",
        is_deliverable: false, 
        category: 'onboarding',
        description: "The Project Manager is officially assigned to the project.",
        type: "Internal",
        axis: "Client Management Axis",
        dependencies: [2],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 5, 
        name: "Setup Drive Folder & Initial Docs",
        formal_name: "Project Directory and Documentation Initialization",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Create the shared Google Drive folder and populate initial templates.",
        type: "Internal",
        axis: "Client Management Axis",
        dependencies: [4],
        parallel_tracks: [6, 12],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 6, 
        name: "Setup Slack Channel",
        formal_name: "Communication Channel Setup (Slack)",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Create the dedicated Slack channel for project communication.",
        type: "Internal",
        axis: "Client Management Axis",
        dependencies: [4],
        parallel_tracks: [5, 12],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 7, 
        name: "Send Kickoff Email",
        formal_name: "Official Project Commencement Communication",
        is_deliverable: true, 
        category: 'onboarding',
        description: "Official project kickoff email sent to the client.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [5, 6, 12],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 8, 
        name: "Send Email + Ask List PDF",
        formal_name: "Client Materials and Information Request",
        is_deliverable: true, 
        category: 'onboarding',
        description: "Send an email to the client with a detailed list of required materials.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [7],
        blocking_priority: "critical",
        resource_dependency: "client_materials"
    },
    { 
        number_index: 9, 
        name: "Informal Client Visit",
        formal_name: "Staff Visit",
        is_deliverable: false, 
        category: 'onboarding',
        description: "An informal visit to the client's staff to build rapport.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [],
        blocking_priority: "low",
        resource_dependency: "none"
    },
    { 
        number_index: 10, 
        name: "Gantt Chart Update",
        formal_name: "Gantt",
        is_deliverable: true, 
        category: 'onboarding',
        description: "👑 Send Gantt Chart to Client 👑",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 11, 
        name: "KYC (Know Your Client) Completion",
        formal_name: "Know Your Client",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Completing the Know Your Client documentation and process.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 12, 
        name: "CRM Client Page Update",
        formal_name: "CRM Client Page Update",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Updating the client's page in the internal CRM system.",
        type: "Internal",
        axis: "Client Management Axis",
        dependencies: [4],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 13, 
        name: "Internal Kickoff Meeting",
        formal_name: "Internal Kickoff",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Meeting with the internal team to officially kick off the project.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [4],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 14, 
        name: "Marketing Persona Alignment",
        formal_name: "Marketing Sync",
        is_deliverable: false, 
        category: 'onboarding',
        description: "Aligning with the client on marketing personas.",
        type: "External",
        axis: "Business & Internal Axis",
        dependencies: [8],
        blocking_priority: "low",
        resource_dependency: "client_input"
    },
    { 
        number_index: 15, 
        name: "First Weekly Summary",
        formal_name: "First weekly update",
        is_deliverable: true, 
        category: 'onboarding',
        description: "👑 Weekly Summary Email 👑",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [7],
        blocking_priority: "high",
        resource_dependency: "none"
    },

    // Phase 2: Research & Discovery (Steps 16-48)
    { 
        number_index: 16, 
        name: "Research Initiation", 
        formal_name: "Research Initiation",
        is_deliverable: false, 
        category: 'research',
        description: "Formal start of research phase with team briefing",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [8],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 17, 
        name: "Client Material Review", 
        formal_name: "Client Material Review",
        is_deliverable: false, 
        category: 'research',
        description: "Comprehensive analysis of all client-provided materials",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [8],
        blocking_priority: "high",
        resource_dependency: "client_materials"
    },
    { 
        number_index: 18, 
        name: "Stakeholder Interview Prep", 
        formal_name: "Stakeholder Interview Prep",
        is_deliverable: false, 
        category: 'research',
        description: "Preparation of interview questions and scheduling",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [17],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 19, 
        name: "Founder Interviews", 
        formal_name: "Founder Interviews",
        is_deliverable: false, 
        category: 'research',
        description: "Deep-dive interviews with company founders and key leadership",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [18],
        blocking_priority: "high",
        resource_dependency: "client_input"
    },
    { 
        number_index: 20, 
        name: "Investor Interviews", 
        formal_name: "Investor Interviews",
        is_deliverable: false, 
        category: 'research',
        description: "Interviews with key investors to understand market positioning",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [18],
        blocking_priority: "medium",
        resource_dependency: "client_input"
    },
    { 
        number_index: 21, 
        name: "Team Member Interviews", 
        formal_name: "Team Member Interviews",
        is_deliverable: false, 
        category: 'research',
        description: "Interviews with key team members across departments",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [18],
        blocking_priority: "medium",
        resource_dependency: "client_input"
    },
    { 
        number_index: 22, 
        name: "Interview Synthesis", 
        formal_name: "Interview Synthesis",
        is_deliverable: false, 
        category: 'research',
        description: "Analysis and synthesis of all interview insights",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [19, 20, 21],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 23, 
        name: "SOW Details Table", 
        formal_name: "SOW Details Table",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Detailed breakdown of scope of work with timelines 👑",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [17],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 24, 
        name: "Market Research Plan", 
        formal_name: "Market Research Plan",
        is_deliverable: false, 
        category: 'research',
        description: "Strategic plan for comprehensive market analysis",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [17],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 25, 
        name: "Competitor Identification", 
        formal_name: "Competitor Identification",
        is_deliverable: false, 
        category: 'research',
        description: "Comprehensive mapping of direct and indirect competitors",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [24],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 26, 
        name: "Competitor Messaging Analysis", 
        formal_name: "Competitor Messaging Analysis",
        is_deliverable: false, 
        category: 'research',
        description: "Analysis of competitor positioning and messaging strategies",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [25],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 27, 
        name: "Competitor Visual Analysis", 
        formal_name: "Competitor Visual Analysis",
        is_deliverable: false, 
        category: 'research',
        description: "Visual identity and design analysis of key competitors",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [25],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 28, 
        name: "Introductory Memo", 
        formal_name: "Introductory Memo",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Initial insights and findings summary document 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [22, 23],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 29, 
        name: "Audience Persona Research", 
        formal_name: "Audience Persona Research",
        is_deliverable: false, 
        category: 'research',
        description: "Deep research into target audience behaviors and preferences",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [24],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 30, 
        name: "Industry Trends Analysis", 
        formal_name: "Industry Trends Analysis",
        is_deliverable: false, 
        category: 'research',
        description: "Comprehensive analysis of current and emerging industry trends.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [24],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 31, 
        name: "Competitive Analysis", 
        formal_name: "Competitive Analysis",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Comprehensive competitive landscape analysis and positioning 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [26, 27],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 32, 
        name: "Internal Research Review", 
        formal_name: "Internal Research Review",
        is_deliverable: false, 
        category: 'research',
        description: "Internal team review of all research findings.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [28, 31],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 33, 
        name: "Narrative Analysis", 
        formal_name: "Narrative Analysis",
        is_deliverable: false, 
        category: 'research',
        description: "Analysis of current brand narrative and story gaps.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [22, 29],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 34, 
        name: "Naming Strategy", 
        formal_name: "Naming Strategy",
        is_deliverable: false, 
        category: 'research',
        description: "Strategic approach to product and company naming.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [32, 33],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 35, 
        name: "Naming Deck", 
        formal_name: "Naming Deck",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Comprehensive naming options with rationale and research 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [34],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 36, 
        name: "URL & Trademark Check", 
        formal_name: "URL & Trademark Check",
        is_deliverable: false, 
        category: 'research',
        description: "Legal and domain availability verification for naming options.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [35],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 37, 
        name: "Final Name Selection", 
        formal_name: "Final Name Selection",
        is_deliverable: false, 
        category: 'research',
        description: "Client decision and confirmation of final name choice.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [35],
        blocking_priority: "high",
        resource_dependency: "client_input"
    },
    { 
        number_index: 38, 
        name: "USP Workshop Prep", 
        formal_name: "USP Workshop Prep",
        is_deliverable: false, 
        category: 'research',
        description: "Preparation materials and agenda for USP workshop.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [32],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 39, 
        name: "Client Pre-Workshop Briefing", 
        formal_name: "Client Pre-Workshop Briefing",
        is_deliverable: false, 
        category: 'research',
        description: "Pre-workshop briefing to align expectations and objectives.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [38],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 40, 
        name: "Internal Pre-Workshop Sync", 
        formal_name: "Internal Pre-Workshop Sync",
        is_deliverable: false, 
        category: 'research',
        description: "Final internal alignment before conducting USP workshop.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [38],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 41, 
        name: "Persona Definition", 
        formal_name: "Persona Definition",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Detailed target audience personas with insights and behaviors 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [29],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 42, 
        name: "Customer Journey Mapping", 
        formal_name: "Customer Journey Mapping",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Comprehensive customer journey with touchpoints and pain points 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [29],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 43, 
        name: "Content Audit", 
        formal_name: "Content Audit",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Analysis of existing content assets and recommendations 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [8],
        blocking_priority: "medium",
        resource_dependency: "client_materials"
    },
    { 
        number_index: 44, 
        name: "SEO Keyword Research", 
        formal_name: "SEO Keyword Research",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Strategic keyword research and SEO recommendations 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [24],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 45, 
        name: "Brand Perception Survey", 
        formal_name: "Brand Perception Survey",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Current brand perception analysis and insights 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [17],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 46, 
        name: "Internal Brand Audit", 
        formal_name: "Internal Brand Audit",
        is_deliverable: false, 
        category: 'research',
        description: "Internal assessment of current brand assets and positioning.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [17],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 47, 
        name: "Research Insights Summary", 
        formal_name: "Research Insights Summary",
        is_deliverable: false, 
        category: 'research',
        description: "Internal consolidation of all research phase findings.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [22, 31, 41, 42, 43, 44, 45, 46],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 48, 
        name: "Pre-USP Workshop Summary", 
        formal_name: "Pre-USP Workshop Summary",
        is_deliverable: true, 
        category: 'research',
        description: "👑 Comprehensive research summary preparing for strategy phase 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [39, 40, 47],
        blocking_priority: "critical",
        resource_dependency: "none"
    },

    // Phase 3: Strategy & USP Development (Steps 49-63)
    { 
        number_index: 49, 
        name: "USP Workshop Deck Pt. 1", 
        formal_name: "USP Workshop Deck Pt. 1",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 First part of USP workshop presentation with research insights 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [48],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 50, 
        name: "USP Workshop Deck Pt. 2", 
        formal_name: "USP Workshop Deck Pt. 2",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Second part of USP workshop with strategic recommendations 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [49],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 51, 
        name: "Present and Deliver USP MEMO",
        formal_name: "Unique Selling Proposition Memorandum of Understanding",
        is_deliverable: true, 
        category: 'strategy',
        description: "The final, approved Unique Selling Proposition memo. This is the master key for all creative work.",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [49, 50],
        blocking_priority: "critical",
        resource_dependency: "roee_approval"
    },
    { 
        number_index: 52, 
        name: "Creative Handover", 
        formal_name: "Creative Handover",
        is_deliverable: false, 
        category: 'strategy',
        description: "Strategic briefing and handover to creative team.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [51],
        blocking_priority: "critical",
        resource_dependency: "none"
    },
    { 
        number_index: 53, 
        name: "Internal Brainstorming", 
        formal_name: "Internal Brainstorming",
        is_deliverable: false, 
        category: 'strategy',
        description: "Internal creative and strategic brainstorming sessions.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [52],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 54, 
        name: "Tone & Voice Development", 
        formal_name: "Tone & Voice Development",
        is_deliverable: false, 
        category: 'strategy',
        description: "Development of brand voice and communication style.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [51],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 55, 
        name: "Brand Voice Workshop", 
        formal_name: "Brand Voice Workshop",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Interactive workshop to define and align on brand voice 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [54],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 56, 
        name: "Brand Messaging Pillars", 
        formal_name: "Brand Messaging Pillars",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Core messaging framework and communication pillars 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 55],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 57, 
        name: "Strategic Initiatives Presentation", 
        formal_name: "Strategic Initiatives Presentation",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Comprehensive strategic recommendations and action plan 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 58, 
        name: "Feature Naming", 
        formal_name: "Feature Naming",
        is_deliverable: false, 
        category: 'strategy',
        description: "Strategic naming of product features and capabilities.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [51, 37],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 59, 
        name: "Product Nomenclature", 
        formal_name: "Product Nomenclature",
        is_deliverable: false, 
        category: 'strategy',
        description: "Comprehensive naming system for product ecosystem.",
        type: "Internal",
        axis: "Strategy & Research Axis",
        dependencies: [51, 37],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 60, 
        name: "Brand Architecture", 
        formal_name: "Brand Architecture",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Comprehensive brand structure and hierarchy framework 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 37],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 61, 
        name: "Elevator Pitch & Taglines", 
        formal_name: "Elevator Pitch & Taglines",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Concise brand messaging and memorable taglines 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 56],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 62, 
        name: "Value Proposition Canvas", 
        formal_name: "Value Proposition Canvas",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Visual framework mapping value proposition to customer needs 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 63, 
        name: "Naming Memo", 
        formal_name: "Naming Memo",
        is_deliverable: true, 
        category: 'strategy',
        description: "👑 Final naming decisions with rationale and implementation guide 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [37],
        blocking_priority: "high",
        resource_dependency: "none"
    },

    // Phase 4: Creative Execution & Brand Activation (Steps 64-99)
    { 
        number_index: 64, 
        name: "Creative Kickoff", 
        formal_name: "Creative Kickoff",
        is_deliverable: false, 
        category: 'brand_building',
        description: "Official start of creative development phase with team alignment.",
        type: "Internal",
        axis: "Creative Axis",
        dependencies: [52],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 65, 
        name: "Moodboard Presentation", 
        formal_name: "Moodboard Presentation",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Visual direction and aesthetic exploration presentation 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [64],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 66, 
        name: "Mid-Project Sync", 
        formal_name: "Mid-Project Sync",
        is_deliverable: false, 
        category: 'brand_building',
        description: "Mid-project review and alignment meeting with leadership.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [65],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 67, 
        name: "Tone and Voice Guide", 
        formal_name: "Tone and Voice Guide",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Comprehensive brand voice and communication guidelines 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [55, 56],
        blocking_priority: "critical",
        resource_dependency: "none"
    },
    { 
        number_index: 68, 
        name: "Visual Concept R1", 
        formal_name: "Visual Concept R1",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 First round of visual identity concepts and exploration 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [65],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 69, 
        name: "Visual Concept R2", 
        formal_name: "Visual Concept R2",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Refined visual identity concepts based on feedback 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [68],
        blocking_priority: "high",
        resource_dependency: "client_input"
    },
    { 
        number_index: 70, 
        name: "Logo Design & Iterations", 
        formal_name: "Logo Design & Iterations",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Final logo design with variations and applications 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [69],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 71, 
        name: "Out of Stealth Plan", 
        formal_name: "Out of Stealth Plan",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Strategic plan for company's public market entry 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [57],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 72, 
        name: "Launch Communications Plan", 
        formal_name: "Launch Communications Plan",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Comprehensive launch communication strategy and timeline 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [71],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 73, 
        name: "PR & Media List", 
        formal_name: "PR & Media List",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Curated media contacts and PR outreach strategy 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [72],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 74, 
        name: "Social Media Strategy", 
        formal_name: "Social Media Strategy",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Comprehensive social media strategy and content plan 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [72],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 75, 
        name: "Content Marketing Plan", 
        formal_name: "Content Marketing Plan",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Strategic content marketing roadmap and editorial calendar 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [67, 56],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 76, 
        name: "Website Sitemap & UX", 
        formal_name: "Website Sitemap & UX",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Website architecture and user experience framework 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [51, 67],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 77, 
        name: "Demo Video Script", 
        formal_name: "Demo Video Script",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Professional demo video script and storyboard 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [51, 67],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 78, 
        name: "Sales Deck Outline", 
        formal_name: "Sales Deck Outline",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Strategic sales presentation structure and messaging 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 67],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 79, 
        name: "Brochure Content Draft", 
        formal_name: "Brochure Content Draft",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Marketing brochure content and messaging framework 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 67],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 80, 
        name: "Stationery Design", 
        formal_name: "Stationery Design",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Business cards, letterhead, and corporate stationery design 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [70],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 81, 
        name: "Homepage Design (UI)", 
        formal_name: "Homepage Design (UI)",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Homepage user interface design and visual layout 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [70, 76],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 82, 
        name: "Sales Deck Design", 
        formal_name: "Sales Deck Design",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Professional sales presentation design and visual assets 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [70, 78],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 83, 
        name: "Brochure Design", 
        formal_name: "Brochure Design",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Marketing brochure design and visual implementation 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [70, 79],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 84, 
        name: "Iconography Set", 
        formal_name: "Iconography Set",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Custom icon set and visual symbol system 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [70],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 85, 
        name: "Full Website Design (UI)", 
        formal_name: "Full Website Design (UI)",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Complete website design across all key pages 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [81],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 86, 
        name: "Demo Video Production", 
        formal_name: "Demo Video Production",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Professional demo video production and post-production 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [77],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 87, 
        name: "Design Visual Identity / Brandbook",
        formal_name: "Comprehensive Brand Identity and Style Guide",
        is_deliverable: true, 
        category: 'brand_building',
        description: "The complete visual identity system and brand guidelines.",
        type: "External",
        axis: "Creative Axis",
        dependencies: [67, 68, 69],
        blocking_priority: "critical",
        resource_dependency: "none"
    },
    { 
        number_index: 88, 
        name: "Merchandise Design", 
        formal_name: "Merchandise Design",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Branded merchandise and promotional materials design 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [87],
        blocking_priority: "low",
        resource_dependency: "none"
    },
    { 
        number_index: 89, 
        name: "Video Testimonials", 
        formal_name: "Video Testimonials",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Customer testimonial videos and social proof content 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [8],
        blocking_priority: "medium",
        resource_dependency: "client_input"
    },
    { 
        number_index: 90, 
        name: "Website Development", 
        formal_name: "Website Development",
        is_deliverable: false, 
        category: 'brand_collaterals',
        description: "Technical website development and implementation.",
        type: "Internal",
        axis: "Creative Axis",
        dependencies: [85, 67],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 91, 
        name: "Website QA", 
        formal_name: "Website QA",
        is_deliverable: false, 
        category: 'brand_collaterals',
        description: "Quality assurance testing and bug fixes.",
        type: "Internal",
        axis: "Creative Axis",
        dependencies: [90],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 92, 
        name: "Website Content Entry", 
        formal_name: "Website Content Entry",
        is_deliverable: false, 
        category: 'brand_collaterals',
        description: "Content management and website population.",
        type: "Internal",
        axis: "Creative Axis",
        dependencies: [90, 67],
        blocking_priority: "high",
        resource_dependency: "client_materials"
    },
    { 
        number_index: 93, 
        name: "Website Go-Live", 
        formal_name: "Website Go-Live",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Official website launch and public availability 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [91, 92],
        blocking_priority: "critical",
        resource_dependency: "none"
    },
    { 
        number_index: 94, 
        name: "Social Media Templates", 
        formal_name: "Social Media Templates",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Social media post templates and visual assets 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [87, 74],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 95, 
        name: "Email Signature Design", 
        formal_name: "Email Signature Design",
        is_deliverable: true, 
        category: 'brand_collaterals',
        description: "👑 Professional email signature templates for team 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [87],
        blocking_priority: "low",
        resource_dependency: "none"
    },
    { 
        number_index: 96, 
        name: "Full Asset Folder", 
        formal_name: "Full Asset Folder",
        is_deliverable: true, 
        category: 'brand_building',
        description: "👑 Complete organized folder with all brand assets 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [87, 85, 86],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 97, 
        name: "Employer Branding Strategy", 
        formal_name: "Employer Branding Strategy",
        is_deliverable: true, 
        category: 'employer_branding',
        description: "👑 Strategic approach to employer brand and talent attraction 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [51, 67],
        blocking_priority: "high",
        resource_dependency: "none"
    },
    { 
        number_index: 98, 
        name: "Recruitment Materials Design", 
        formal_name: "Recruitment Materials Design",
        is_deliverable: true, 
        category: 'employer_branding',
        description: "👑 Recruitment collateral and employer brand materials 👑",
        type: "External",
        axis: "Creative Axis",
        dependencies: [87, 97],
        blocking_priority: "medium",
        resource_dependency: "none"
    },
    { 
        number_index: 99, 
        name: "LinkedIn Post", 
        formal_name: "LinkedIn Post",
        is_deliverable: true, 
        category: 'brand_activation',
        description: "👑 Professional LinkedIn launch announcement post 👑",
        type: "External",
        axis: "Strategy & Research Axis",
        dependencies: [72, 93],
        blocking_priority: "medium",
        resource_dependency: "none"
    },

    // Phase 5: Project Closure & Handover (Steps 100-104)
    { 
        number_index: 100, 
        name: "Celebration Cake & Gifts", 
        formal_name: "Celebration Cake & Gifts",
        is_deliverable: true, 
        category: 'project_closure',
        description: "👑 Project completion celebration and branded gifts 👑",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [93],
        blocking_priority: "low",
        resource_dependency: "none"
    },
    { 
        number_index: 101, 
        name: "Brand Reveal Event", 
        formal_name: "Brand Reveal Event",
        is_deliverable: false, 
        category: 'project_closure',
        description: "Official brand launch event planning and coordination.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [93],
        blocking_priority: "low",
        resource_dependency: "client_input"
    },
    { 
        number_index: 102, 
        name: "Client Testimonial Request", 
        formal_name: "Client Testimonial Request",
        is_deliverable: false, 
        category: 'project_closure',
        description: "Request for client testimonial and case study approval.",
        type: "External",
        axis: "Client Management Axis",
        dependencies: [93],
        blocking_priority: "low",
        resource_dependency: "client_input"
    },
    { 
        number_index: 103, 
        name: "Project Retrospective", 
        formal_name: "Project Retrospective",
        is_deliverable: false, 
        category: 'project_closure',
        description: "Internal project review and lessons learned session.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [93],
        blocking_priority: "low",
        resource_dependency: "none"
    },
    { 
        number_index: 104, 
        name: "Post-Mortem Meeting",
        formal_name: "Project Retrospective and Lessons Learned Analysis",
        is_deliverable: false, 
        category: 'project_closure',
        description: "Internal team meeting to discuss project successes and areas for improvement.",
        type: "Internal",
        axis: "Business & Internal Axis",
        dependencies: [103],
        blocking_priority: "low",
        resource_dependency: "none"
    }
];

export const deliverablesByPhase = [
  {
    phase: "Phase 1: Project Initiation & Setup",
    total: 6,
    deliverables: [
      { name: "Price Quote", step: 1, tags: ["Business", "Internal", "Contract", "Financial"], axis: "Business & Internal", priority: "Critical", note: "Blocks entire project" },
      { name: "Signed Contract from Both Parties", step: 2, tags: ["Business", "Internal", "Contract", "Legal"], axis: "Business & Internal", priority: "Critical", note: "Master dependency" },
      { name: "Kickoff Email", step: 7, tags: ["Communication", "External", "Project Setup"], axis: "Client Management", priority: "High" },
      { name: "Email + Ask List PDF", step: 8, tags: ["Communication", "External", "Information Gathering"], axis: "Client Management", priority: "High", note: "Blocks research phase" },
      { name: "Gantt Chart", step: 10, tags: ["Planning", "Timeline", "External"], axis: "Client Management", priority: "Medium" },
      { name: "Weekly Summary Email", step: 15, tags: ["Communication", "Recurring", "External"], axis: "Client Management", priority: "Medium" },
    ],
  },
  {
    phase: "Phase 2: Research & Discovery",
    total: 8,
    deliverables: [
      { name: "Client Kickoff Summary Email", step: 17, tags: ["Communication", "Meeting Summary", "External"], axis: "Client Management", priority: "Medium" },
      { name: "Brand V0 Action Plan and Deliverables", step: 18, tags: ["Planning", "Strategy", "Conditional"], axis: "Client Management", priority: "Low", note: "Optional - Only if decided to proceed" },
      { name: "Initial Deliverables Table", step: 19, tags: ["Planning", "Quick Wins", "Conditional"], axis: "Client Management", priority: "Low", note: "Optional - Only if decided to proceed" },
      { name: "SOW Details Table", step: 23, tags: ["Documentation", "Process", "External"], axis: "Client Management", priority: "High" },
      { name: "Introductory Memo", step: 28, tags: ["Research", "Strategy", "External"], axis: "Client Management", priority: "High" },
      { name: "Competitive Analysis", step: 31, tags: ["Research", "Strategy", "Market Analysis"], axis: "Strategy & Research", priority: "High" },
      { name: "Naming Deck", step: 35, tags: ["Creative", "Strategy", "Branding"], axis: "Creative", priority: "Medium", note: "Delivered only after naming session" },
      { name: "Pre-USP Workshop Summary + First Act Presentation", step: 48, tags: ["Strategy", "Workshop Prep", "Internal Review"], axis: "Strategy & Research", priority: "Critical", note: "USP dependency" },
    ],
  },
  {
    phase: "Phase 3: Strategy & USP Development",
    total: 10, 
    deliverables: [
      { name: "USP Workshop Deck Pt. 1", step: 49, tags: ["Strategy", "Workshop", "Presentation"], axis: "Strategy & Research", priority: "High" },
      { name: "USP Workshop Deck Pt. 2", step: 50, tags: ["Strategy", "Workshop", "Presentation"], axis: "Strategy & Research", priority: "High" },
      { name: "USP Memo", step: 51, tags: ["Strategy", "Documentation", "Core"], axis: "Strategy & Research", priority: "Critical", note: "Core deliverable" },
      { name: "Brand Voice Workshop", step: 55, tags: ["Strategy", "Branding", "Workshop"], axis: "Strategy & Research", priority: "High" },
      { name: "Brand Messaging Pillars", step: 56, tags: ["Strategy", "Messaging", "Branding"], axis: "Strategy & Research", priority: "High" },
      { name: "Strategic Initiatives Presentation", step: 57, tags: ["Strategy", "Presentation", "Action Plan"], axis: "Strategy & Research", priority: "High" },
      { name: "Brand Architecture", step: 60, tags: ["Strategy", "Branding", "Structure"], axis: "Strategy & Research", priority: "High" },
      { name: "Elevator Pitch & Taglines", step: 61, tags: ["Messaging", "Branding", "Communication"], axis: "Strategy & Research", priority: "Medium" },
      { name: "Value Proposition Canvas", step: 62, tags: ["Strategy", "Business Model", "Value"], axis: "Strategy & Research", priority: "High" },
      { name: "Naming Memo", step: 63, tags: ["Naming", "Branding", "Documentation"], axis: "Strategy & Research", priority: "High" },
    ],
  },
  {
    phase: "Phase 4: Creative Execution & Brand Activation",
    total: 31,
    deliverables: [
      { name: "Moodboard Presentation", step: 65, tags: ["Creative", "Visual", "Inspiration"], axis: "Creative", priority: "High" },
      { name: "Tone and Voice Guide", step: 67, tags: ["Branding", "Messaging", "Guidelines"], axis: "Strategy & Research", priority: "Critical", note: "Blocks all copywriting" },
      { name: "Visual Concept R1", step: 68, tags: ["Creative", "Visual Identity", "Concepts"], axis: "Creative", priority: "High" },
      { name: "Visual Concept R2", step: 69, tags: ["Creative", "Visual Identity", "Refinement"], axis: "Creative", priority: "High" },
      { name: "Logo Design & Iterations", step: 70, tags: ["Creative", "Logo", "Branding"], axis: "Creative", priority: "High" },
      { name: "Out of Stealth Plan", step: 71, tags: ["Strategy", "Launch", "PR"], axis: "Strategy & Research", priority: "High" },
      { name: "Launch Communications Plan", step: 72, tags: ["Communication", "Launch", "Strategy"], axis: "Strategy & Research", priority: "High" },
      { name: "PR & Media List", step: 73, tags: ["PR", "Media Relations", "Strategy"], axis: "Strategy & Research", priority: "High" },
      { name: "Social Media Strategy", step: 74, tags: ["Digital Marketing", "Social Media", "Strategy"], axis: "Strategy & Research", priority: "High" },
      { name: "Content Marketing Plan", step: 75, tags: ["Digital Marketing", "Content", "Strategy"], axis: "Strategy & Research", priority: "High" },
      { name: "Website Sitemap & UX", step: 76, tags: ["Web", "UX", "Planning"], axis: "Creative", priority: "High" },
      { name: "Demo Video Script", step: 77, tags: ["Video", "Content", "Marketing"], axis: "Creative", priority: "High" },
      { name: "Sales Deck Outline", step: 78, tags: ["Sales", "Presentation", "Strategy"], axis: "Strategy & Research", priority: "Medium" },
      { name: "Brochure Content Draft", step: 79, tags: ["Content", "Marketing", "Collateral"], axis: "Strategy & Research", priority: "Medium" },
      { name: "Stationery Design", step: 80, tags: ["Design", "Collateral", "Print"], axis: "Creative", priority: "Medium" },
      { name: "Homepage Design (UI)", step: 81, tags: ["Web", "UI", "Design"], axis: "Creative", priority: "High" },
      { name: "Sales Deck Design", step: 82, tags: ["Sales", "Presentation", "Design"], axis: "Creative", priority: "High" },
      { name: "Brochure Design", step: 83, tags: ["Design", "Collateral", "Print"], axis: "Creative", priority: "High" },
      { name: "Iconography Set", step: 84, tags: ["Design", "Visual Identity", "Icons"], axis: "Creative", priority: "High" },
      { name: "Full Website Design (UI)", step: 85, tags: ["Web", "UI", "Design", "Comprehensive"], axis: "Creative", priority: "High" },
      { name: "Demo Video Production", step: 86, tags: ["Video", "Production", "Marketing"], axis: "Creative", priority: "High" },
      { name: "Visual Identity/Brandbook", step: 87, tags: ["Branding", "Guidelines", "Core"], axis: "Creative", priority: "Critical", note: "Core brand asset" },
      { name: "Merchandise Design", step: 88, tags: ["Design", "Merchandise", "Branding"], axis: "Creative", priority: "Low" },
      { name: "Video Testimonials", step: 89, tags: ["Content", "Social Proof", "Marketing"], axis: "Creative", priority: "Medium" },
      { name: "Website Go-Live", step: 93, tags: ["Web", "Launch", "Deployment"], axis: "Creative", priority: "Critical", note: "Public launch" },
      { name: "Social Media Templates", step: 94, tags: ["Social Media", "Design", "Templates"], axis: "Creative", priority: "Medium" },
      { name: "Email Signature Design", step: 95, tags: ["Design", "Communication", "Internal"], axis: "Creative", priority: "Low" },
      { name: "Full Asset Folder", step: 96, tags: ["Assets", "Delivery", "Archive"], axis: "Creative", priority: "High" },
      { name: "Employer Branding Strategy", step: 97, tags: ["HR", "Recruitment", "Strategy"], axis: "Strategy & Research", priority: "High" },
      { name: "Recruitment Materials Design", step: 98, tags: ["HR", "Recruitment", "Design"], axis: "Creative", priority: "Medium" },
      { name: "LinkedIn Post", step: 99, tags: ["Social Media", "Launch", "Communication"], axis: "Strategy & Research", priority: "Medium" },
    ],
  },
  {
    phase: "Phase 5: Project Closure & Handover",
    total: 1, 
    deliverables: [
      { name: "Celebration Cake & Gifts", step: 100, tags: ["Client Management", "Engagement", "Closure"], axis: "Client Management", priority: "Low" },
    ],
  },
];

export const summaries = {
  criticalPath: [
    { name: "Signed Contract", step: 2, reason: "Nothing starts without this" },
    { name: "Email + Ask List PDF", step: 8, reason: "Blocks all research" },
    { name: "USP MEMO", step: 51, reason: "Unlocks all creative work" },
    { name: "Tone And Voice Guide", step: 67, reason: "Blocks all copywriting" },
    { name: "Visual Identity / Brandbook", step: 87, reason: "Blocks final production" }
  ],
  specialApproval: {
    roee: [
        { name: "Pre-USP Workshop Summary", step: 48 },
        { name: "USP Workshop Decks", step: "49-50" },
        { name: "USP MEMO", step: 51 },
        { name: "SOW Summary Presentation", step: 97 }
    ],
    conditional: [
        { name: "Brand V0 Action Plan", step: 18, reason: "Only if V0 is pursued" },
        { name: "Initial Deliverables Table", step: 19, reason: "Only if immediate needs exist" },
        { name: "Animation Video Script", step: 74, reason: "Based on client decision" }
    ]
  }
};
